name: Deploy to Heroku Hosting on PR

"on": pull_request

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "kurester"
          heroku_email: "thanathip.suw@ku.th"
          usedocker: true
